// <auto-generated />
using System;
using BlazorAppAccountManager.Components.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorAppAccountManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251028072657_AddCertificateRecordReferenceFields")]
    partial class AddCertificateRecordReferenceFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppAccountManager.Components.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Certificate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CertificateRecordId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CertificationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfDocumentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceCertifateId")
                        .HasColumnType("longtext");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CertificateRecordId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.CertificateRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CertificateType")
                        .HasColumnType("int");

                    b.Property<string>("LatestCertificateId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceCertificateRecordId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("UsingReference")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceCertificateRecordId");

                    b.HasIndex("SupplierId", "CertificateType")
                        .IsUnique();

                    b.ToTable("CertificateRecords");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Lamp", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Lamps");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.LampTemplate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LampTemplates");

                    b.HasData(
                        new
                        {
                            Id = "d3460946-44c0-4c0b-b5df-abea4dbb4cc9",
                            Name = "Զ��",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = "b9618d88-5fdf-4a4e-b506-43478aae618b",
                            Name = "����",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = "f8a0e833-be53-4aa5-9c41-bc13335ed611",
                            Name = "ǰ����",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = "b4020f11-18d9-4a23-bb87-39213388c016",
                            Name = "�����ʻ��",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = "c3f05435-e5b4-46e5-af47-b7815b75105f",
                            Name = "ǰλ�õ�",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = "123afbd4-67a0-4744-aed7-76675d2b846a",
                            Name = "ǰת���",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = "571bbae7-17dd-4619-85f9-d6ed1a26c1b5",
                            Name = "�ǵ�",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = "5ccf6dce-7b72-4adb-bb1f-32bd7fef4c97",
                            Name = "�ƶ���",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = "e7fa78b3-2b14-43ae-8103-6bdd101db365",
                            Name = "��ת���",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = "b359277f-c794-476b-b714-fbdaaadb1eba",
                            Name = "��λ�õ�",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = "500c1347-01c3-48a9-845b-d6ff57c3dcc1",
                            Name = "������",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = "d9728219-9010-474d-b999-e9b93f837d1c",
                            Name = "������",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = "e36c9118-ce9a-4852-b09f-f96f30121c14",
                            Name = "��λ�ƶ���",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = "8421c8a4-f13c-47f1-861f-fb2ea063d985",
                            Name = "���յ�",
                            SortOrder = 14
                        });
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.PdfDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("PdfDocuments");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SopTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Supplier", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LampId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReferenceSupplierId")
                        .HasColumnType("longtext");

                    b.Property<bool>("UsingReference")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("LampId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Certificate", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Models.CertificateRecord", null)
                        .WithMany("Certificates")
                        .HasForeignKey("CertificateRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAppAccountManager.Components.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.CertificateRecord", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Models.CertificateRecord", "ReferenceCertificateRecord")
                        .WithMany()
                        .HasForeignKey("ReferenceCertificateRecordId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BlazorAppAccountManager.Components.Models.Supplier", "Supplier")
                        .WithMany("CertificateRecords")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReferenceCertificateRecord");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Lamp", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Models.Project", "Project")
                        .WithMany("Lamps")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Project", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Data.ApplicationUser", "Creator")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Supplier", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Models.Lamp", "Lamp")
                        .WithMany("Suppliers")
                        .HasForeignKey("LampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lamp");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorAppAccountManager.Components.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BlazorAppAccountManager.Components.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Data.ApplicationUser", b =>
                {
                    b.Navigation("CreatedProjects");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.CertificateRecord", b =>
                {
                    b.Navigation("Certificates");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Lamp", b =>
                {
                    b.Navigation("Suppliers");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Project", b =>
                {
                    b.Navigation("Lamps");
                });

            modelBuilder.Entity("BlazorAppAccountManager.Components.Models.Supplier", b =>
                {
                    b.Navigation("CertificateRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
